baseURL = "https://github.com/sweetbbak.io"
theme = "risotto"
title = "sweet@nixos"
author = "sweetbbak"
copyright = "© [sweetbbak](https://github.com/sweetbbak)"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[params]
noindex = false

[params.theme]
# palette = "base16-dark"
palette = "gruvbox-dark"
# palette = "windows-95"
# palette = "tender"
# palette = "tokyo-night-dark"
# palette = "dracula"
# palette = "material"
# palette = "apprentice"
# palette = "papercolor-dark"
# palette = "gruvbox-light"
# palette = "tokyo-night-light"
# palette = ""

# Sidebar: about/bio
[params.about]
title = "sweetbbak"
description = "just a tiny little blog about programming and my observations."
# logo = "images/rice.svg"
logo = "author.png"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/sweetbbak"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:sweetbabyalaska@gmail.com"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  # [[menu.main]]
  #   identifier = "posts"
  #   name = "Posts"
  #   url = "/posts/"
  #   weight = 12
  # [[menu.main]]
  #   identifier = "~/.config"
  #   name = "Config"
  #   url = "/config/"
  #   weight = 12

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[markup]

  # Table of contents
  # Add toc = true to content front matter to enable
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

# [module]
#   [[module.imports]]
#     path = 'github.com/hugomods/images'
#     disable = false
